image: Visual Studio 2017

branches:
  only:
    - develop
    - master

skip_tags: true

environment:
  JAVA_HOME: c:/Program Files/Java/jdk1.8.0
  
  sonar_login:
    secure: 6qD93a8X/HlviVML1h7oaD5Z57iWiGc6BLkgizomSUHAgcNeC6eQoY8sprEtlHtN
  
  coverlet_output: "%APPVEYOR_BUILD_FOLDER%/build/Coverlet.Coverage.OpenCover.xml"
  
  CODECOV_TOKEN:
    secure: qpg2oUby8/m76bjOwVR+hoiGl5/k2CzSDtXnXoog0eZvvgC8k34Yj+IAUedg0yOM
  
build: off
test: off

before_build:
  cmd: >-
    choco install gitversion.portable -y
    
    gitversion /l console /output buildserver /updateAssemblyInfo
    
    choco install codecov
    
    dotnet tool install --global dotnet-sonarscanner
    
    dotnet restore src
    
build_script:
  ps: >-
    if ("$env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "")
    {
      dotnet sonarscanner begin /k:"adz21c_Periturf" /o:"adz21c-github" /v:"$env:GitVersion_FullSemVer" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.branch.name="$env:APPVEYOR_REPO_BRANCH"
    }
    else
    {
      dotnet sonarscanner begin /k:"adz21c_Periturf" /o:"adz21c-github" /v:"$env:GitVersion_FullSemVer" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.pullrequest.key="$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:sonar.pullrequest.branch="$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH" /d:sonar.pullrequest.base="$env:APPVEYOR_REPO_BRANCH"
    }
    
    dotnet build src
    
    dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="$env:coverlet_output"
    
    dotnet sonarscanner end /d:sonar.login="$env:sonar_login"
    
    codecov -f "$env:coverlet_output" -t "$env:CODECOV_TOKEN"
    
    dotnet pack src --no-restore --include-symbols -c Release -p:PackageVersion=$env:GitVersion_NuGetVersionV2

artifacts:
- path: '**\bin\Release\*.nupkg'
  name: NuGetPackage

deploy:
- provider: NuGet
  api_key:
    secure: 7O2m24jX9iGDVqiTgo/BQfilTBo6ZyAJnv2sscOrtIl3sxLFOhXXJhmF1Ra/bmj0
  skip_symbols: true
  artifact: NuGetPackage
  on:
    branch: /master|develop/
