image: Visual Studio 2019

branches:
  only:
    - develop
    - master
    - feature/*

skip_tags: true

environment:
  JAVA_HOME: c:/Program Files/Java/jdk1.8.0
  
  sonar_login:
    secure: 6qD93a8X/HlviVML1h7oaD5Z57iWiGc6BLkgizomSUHAgcNeC6eQoY8sprEtlHtN
  
  CODECOV_TOKEN:
    secure: qpg2oUby8/m76bjOwVR+hoiGl5/k2CzSDtXnXoog0eZvvgC8k34Yj+IAUedg0yOM
  
build: off
test: off

before_build:
  cmd: >-
    choco install gitversion.portable -y --version 4.0.0
    
    gitversion /l console /output buildserver /updateAssemblyInfo
    
    dotnet restore src

build_script:
  ps: >-
    dotnet build src --no-restore -c Release
    
    dotnet pack src --no-restore --no-build --include-symbols -c Release -p:PackageVersion=$env:GitVersion_NuGetVersionV2

artifacts:
- path: '**\bin\Release\*.nupkg'
  name: NuGetPackage

deploy:
- provider: NuGet
  api_key:
    secure: vYMb0LiGindib+iR4OY1PVUDUTf9odWJ1ajb0GDnkb2SnfK+zG/H4KUQp9sN3+Ka
  skip_symbols: true
  artifact: NuGetPackage
  on:
    branch: /master|develop/
