image: Visual Studio 2017
environment:
  JAVA_HOME: c:/Program Files/Java/jdk1.8.0
build_script:
  cmd: >-
    choco install gitversion.portable -pre -y
    
    dotnet tool install --global dotnet-sonarscanner
    
    dotnet restore src
    
    gitversion /l console /output buildserver /updateAssemblyInfo
    
    dotnet sonarscanner begin /k:"adz21c_Periturf" /o:"adz21c-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="52802d649c768a8651be8b82c80f6b5c9e569fae"
    
    dotnet build src
    
    dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
    dotnet sonarscanner end /d:sonar.login="52802d649c768a8651be8b82c80f6b5c9e569fae"
test: off
