image: Visual Studio 2017

branches:
  only:
    - develop
    - master

skip_tags: true

environment:
  JAVA_HOME: c:/Program Files/Java/jdk1.8.0
  
  sonar_login:
    secure: 6qD93a8X/HlviVML1h7oaD5Z57iWiGc6BLkgizomSUHAgcNeC6eQoY8sprEtlHtN
  
  coverlet_output: "%APPVEYOR_BUILD_FOLDER%/build/Coverlet.Coverage.OpenCover.xml"
  
  CODECOV_TOKEN:
    secure: qpg2oUby8/m76bjOwVR+hoiGl5/k2CzSDtXnXoog0eZvvgC8k34Yj+IAUedg0yOM
  
build: off
test: off

before_build:
  cmd: >-
    choco install gitversion.portable -pre -y
    
    gitversion /l console /output buildserver /updateAssemblyInfo
    
    choco install codecov
    
    dotnet tool install --global dotnet-sonarscanner
    
    dotnet restore src
    
build_script:
  cmd: >-
    dotnet sonarscanner begin /k:"adz21c_Periturf" /o:"adz21c-github" /v:"%GitVersion_FullSemVer%" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%sonar_login%" /d:sonar.branch.name="%APPVEYOR_REPO_BRANCH%"
    
    dotnet build src
    
    dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="%coverlet_output%"
    
    dotnet sonarscanner end /d:sonar.login="%sonar_login%"
    
    codecov -f "%coverlet_output%" -t "%CODECOV_TOKEN%"

    dotnet pack --no-restore --no-build --include-symbols -p PackageVersion="%GitVersion_MajorMinorPatch%" --version-suffix "%GitVersion_NuGetPreReleaseTagV2%"
