image: Visual Studio 2017

branches:
  only:
    - develop
    - master

skip_tags: true

environment:
  JAVA_HOME: c:/Program Files/Java/jdk1.8.0
  sonar_login:
    secure: 55o+cj8Gxbhzx5I95wHQVyuVEjpp9LyP2Vp05aHPFKSIeCixBhYfKbVf0J2fBoIs

build: off
test: off

before_build:
  cmd: >-
    choco install gitversion.portable -pre -y
    
    gitversion /l console /output buildserver /updateAssemblyInfo
    
    dotnet tool install --global dotnet-sonarscanner
    
    dotnet restore src
    
build_script:
  cmd: >-
    dotnet sonarscanner begin /k:"adz21c_Periturf" /o:"adz21c-github" /v:"%GitVersion_FullSemVer%" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%sonar_login%"
    
    dotnet build src
    
    dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
    dotnet sonarscanner end /d:sonar.login="%sonar_login%"
