<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FakeItEasy" Version="8.3.0" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="17.12.0" />
    <PackageReference Include="nunit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Periturf.Hosting\Periturf.Hosting.csproj" />
    <ProjectReference Include="..\Periturf\Periturf.csproj" />
  </ItemGroup>

</Project>
