name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    paths:
      - 'src/**'
      - '.github/workflows/ci.yml'
  pull_request:

env:
  CODE_COVERAGE_FILENAME: code-coverage.xml
  UNIT_TEST_FILENAME: unit-tests-report.trx

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      gitversion_informationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}
      gitversion_fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
      gitversion_preReleaseLabel: ${{ steps.gitversion.outputs.preReleaseLabel }}
      tests_outcome: ${{ steps.build.outputs.tests_outcome }}
    env:
      PACKAGE_PATH: ${{ github.workspace }}/artifacts/packages
      UNIT_TEST_REPORTS_PATH: ${{ github.workspace }}/artifacts/unit-test-reports
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'
          preferLatestVersion: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Git version requires complete history and sonarcloud for a better relevancy of analysis

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p .sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path .sonar/scanner

      - name: Restore Tools
        working-directory: src
        run: |
          dotnet tool restore
      
      - name: Build, test, and analyze
        id: build
        working-directory: src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT: ${{ vars.SONAR_PROJECT }}
          SONAR_ORGANISATION: ${{ vars.SONAR_ORGANISATION }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          UNIT_TEST_REPORT: ${{ env.UNIT_TEST_REPORTS_PATH }}/${{ env.UNIT_TEST_FILENAME }}
          COVERAGE_REPORT: ${{ env.UNIT_TEST_REPORTS_PATH }}/${{ env.CODE_COVERAGE_FILENAME }}
        run: |
          echo "build_outcome=skipped" >> "$GITHUB_OUTPUT"
          echo "tests_outcome=skipped" >> "$GITHUB_OUTPUT"

          echo "::group::Setup Sonar Scanner"
          ../.sonar/scanner/dotnet-sonarscanner begin /d:sonar.login="$SONAR_TOKEN" \
            /k:"$SONAR_PROJECT" \
            /o:"$SONAR_ORGANISATION" \
            /v:"$GitVersion_FullSemVer" \
            /d:sonar.host.url="$SONAR_HOST_URL" \
            /d:sonar.scanner.skipJreProvisioning=true \
            /d:sonar.scanner.scanAll=false \
            /d:sonar.cs.vscoveragexml.reportsPaths="$COVERAGE_REPORT"
          echo "::endgroup::"

          echo "::group::Build"
          if dotnet build \
            -c Release \
            -p:Version="$GitVersion_FullSemVer" \
            -p:InformationalVersion="$GitVersion_InformationalVersion"; 
          then
            buildOutcome='success'
          else
            buildOutcome='failure'
          fi
          echo "build_outcome=$buildOutcome" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"

          if [ "$buildOutcome" = 'success' ]; then
            echo "::group::Test"
            if dotnet dotnet-coverage \
              collect "dotnet test ./Periturf.Tests --no-restore --no-build -c Release --logger trx;LogFileName=$UNIT_TEST_REPORT" \
              --settings:'CodeCoverage.runsettings' \
              --output "$COVERAGE_REPORT" \
              --output-format Xml;
            then
              testsOutcome='success'
            else
              testsOutcome='failure'
            fi
            echo "tests_outcome=$testsOutcome" >> "$GITHUB_OUTPUT"
            echo "::endgroup::"
          fi

          echo "::group::Sonar Scanner End"
          ../.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
          echo "::endgroup::"

          [ "$buildOutcome" = 'failure' ] && echo "::error::Build failed" && exit 1
          [ "$testsOutcome" = 'failure' ] && echo "::error::Tests failed" && exit 1
          exit 0

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.build.outputs.tests_outcome != 'failure' }}
        with:
          name: unit tests reports
          path: ${{ env.UNIT_TEST_REPORTS_PATH }}/**
          retention-days: 14
      
      - name: Package
        if: ${{ !cancelled() && steps.build.outputs.build_outcome == 'success' }}
        working-directory: src
        run: |
          dotnet pack . \
            --no-restore \
            --no-build \
            --include-symbols \
            -p:SymbolPackageFormat=snupkg \
            -c Release \
            -p:Version="$GitVersion_FullSemVer" \
            -o "$PACKAGE_PATH"

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ${{ env.PACKAGE_PATH }}/**
          retention-days: 1

  test_report:
    name: Test Report
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ !cancelled() && needs.build.outputs.tests_outcome == 'success' }}
    env:
      UNIT_TEST_REPORTS_PATH: ${{ github.workspace }}/artifacts/unit-test-reports
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: unit tests reports
          path: ${{ env.UNIT_TEST_REPORTS_PATH }}
          
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ${{ env.UNIT_TEST_REPORTS_PATH }}/${{ env.UNIT_TEST_FILENAME }}
  
  #release_github:
  #  name: Create Github Release
  #
  #  needs: [build]
  #  if: ${{ success() && github.event_name == 'push' }}
  #
  #  runs-on: windows-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #       
  #    - name: Download artifacts
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: packages
  #        path: ${{ env.PACKAGE_PATH }}
  #
  #    - name: Create Git Release Tag v${{ needs.build.outputs.gitversion_fullSemVer }}
  #      run: |
  #        git tag v${{ needs.build.outputs.gitversion_fullSemVer }}
  #        git push origin v${{ needs.build.outputs.gitversion_fullSemVer }}
  #
  #    - name: Create Github Release
  #      uses: softprops/action-gh-release@v2
  #      with:
  #        name: ${{ needs.build.outputs.gitversion_informationalVersion }}
  #        files: ${{ env.PACKAGE_PATH }}\*
  #        tag_name: v${{ needs.build.outputs.gitversion_fullSemVer }}
  #        prerelease: ${{ needs.build.outputs.gitversion_preReleaseLabel != '' }}
  #
  #release_nuget:
  #  name: Push Release to Nuget
  #
  #  needs: [build]
  #  if: ${{ success() && github.event_name == 'push' }}
  #
  #  runs-on: windows-latest
  #  steps:
  #    - name: Download artifacts
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: packages
  #        path: ${{ env.PACKAGE_PATH }}
  #
  #    - name: Push to NuGet
  #      run: dotnet nuget push "${{ env.PACKAGE_PATH }}\*" --api-key "${{ secrets.NUGET_APIKEY }}" -s "https://api.nuget.org/v3/index.json"
